project_id = "jfmrvhrpwyxxjpcblavp"

[functions.tavily-search]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.model-compare]
verify_jwt = false

[functions.text-action]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.generate-video]
verify_jwt = false

[functions.process-document]
verify_jwt = false

[functions.enhance-prompt]
verify_jwt = false